### ISSUE TITLE
Les vitesses de vent ne correspondent pas

### ISSUE THREAD

**Issue by hardcore-sushi** [hacf-fr/meteofrance-api#31]
Avec l'API, j'obtiens des valeurs de vitesse de vent en dessous de celles affichées sur le site de Météo France.

Par example 14 au lieu de 40 km/h ou 8 au lieu de 15 km/h.

Est-ce que le problème vient de l'unité de la valeur donnée par l'API (km/h et noeuds ne correspondent pas) ou est-ce qu'il y a un calcul à faire avec cette valeur pour obtenir la vitesse réelle ?

J'utilise le champ `forecast["wind"]["speed"]` pour obtenir la vitesse du vent avec l'API. Est-ce le bon paramètre ou est-ce que je ne sais tout simplement pas utiliser le site de Météo France ?

Edit:
Il semblerai qu'en prenant le double de la valeur de l'API puis en la convertissant en km/h, on trouve la bonne valeur. Est-ce la bonne solution ?

**Comment by oncleben31** [comment]
Merci pour remonter ce problème. Juste pour être sur tu ne compare pas la vitesse du vent avec la vitesse des rafales de l'appli ?

J'ai regardé si ca pouvait êter une conversion du type m/s en km/h. Mais le rapport est de 3.6. Ca ne semble pas être ca. Il va falloir que j'investigue plus.

Peux tu vérifier si dans ton cas ce n'est pas non plus en décalage dans le temps ? Comme si la vitesse indiqué était celle de l'heure d'avant ou d'après ?

Peux tu aussi partager pour quel lieux tu constates ce problème ?

**Comment by hardcore-sushi** [comment]
Je compare les données de l'API à celles du site pas de l'appli, et les valeurs ne correspondent pas non plus aux rafales.
Le problème n'a pas l'air de venir des horraires car les variations correspondent plutôt bien.

J'ai tester avec plusieurs lieux (Calais, Biarritz...). Le problème semble être toujours la.

**Comment by oncleben31** [comment]
Ah OK, je comprend j'ai supposé que tu utilisais Home Assistant. Et après vérification c'est OK dans HA.
L'API seule renvoie la vitesse du vent en m/s. Il faut multiplier par 3.6. 
Et sur le site de Météo-France la vitesse du vent est arrondi à 5 km/h près.

Peux tu confirmer que tu retombes sur des valeurs similaires avec la conversion et l'arrondi ?

**Comment by hardcore-sushi** [comment]
La conversion m/s vers km/h semble correspondre. En revanche, les arrondis du site semble toujours se faire par excès (un peu étrange mais pourquoi pas).
En tout cas merci pour cette info.
Au passage, cette librairie est géniale :+1:
