### ISSUE TITLE
Générer son propre token ?

### ISSUE THREAD

**Issue by LoganTann** [hacf-fr/meteofrance-api#340]
**Is your feature request related to a problem? Please describe.**
Bonjour, c'est un superbe projet ! Le code est vraiment simple à comprendre, c'est très utile car je suis actuellement en train d'utiliser cette API sur Javascript.

Je voudrais savoir, y a-t-il un moyen automatique pour générer son propre token plutôt que d'utiliser celui du repo ? À moins que celui-ci est fiable ?

**Describe the solution you'd like**
Une méthode permettant de retourner un nouveau token pour utiliser l'API.

**Describe alternatives you've considered**
Utiliser le token fourni par le repo, et espérer qu'il fonctionne assez longtemps.

**Comment by dx44** [comment]
Ce token est fourni 'gracieusement' mais la procédure d'obtention d'un nouveau token est décrit dans un [document officiel](https://donneespubliques.meteofrance.fr/client/gfx/utilisateur/File/documentation-webservices-inspire.pdf) publié par Météo France et suivant la directive européene INSPIRE.
Donc cela pourrait être automatisé en ayant en input un login/mdp. Tu peux proposer un PR si tu sais/veux faire.
