### ISSUE TITLE
Use the v2/observation API endpoint

### ISSUE THREAD

**Issue by bbesset** [hacf-fr/meteofrance-api#521]
**Is your feature request related to a problem? Please describe.**
The [meteo-france](https://github.com/home-assistant/core/blob/dev/homeassistant/components/meteo_france/weather.py#L128) component in home-assistant uses current_forecast as temperature. Resulting values are discontinuous :

![image](https://user-images.githubusercontent.com/2285983/208506326-4837c439-6dca-4636-90c3-eca488df7b25.png)

I think it is due `current_forecast` oscillating between observation and next forecasted temperature.

**Describe the solution you'd like**
A continous temperature.

**Describe alternatives you've considered**
The v2/observation API endpoint returns latest observation. I think it would be nice to expose it as a new method in `client.py`.
I've created a PR #520

**Comment by Quentame** [comment]
Nice observations !
